name: Releasing Node App
#   FOR TESTING PURPOSES ONLY
on:
    push:
        branches:
            - master
# on:
#     create:
#         tags:
#             - v*
jobs:
    test:
        name: Test on node ${{ matrix.node_version }} and ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                node_version: [11, 12, 13]
                os: [ubuntu-latest, macOS-latest]
        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js ${{ matrix.node_version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node_version }}

            - name: install mhy
              run: npm i -g mhy@latest

            - name: npm install, build and test
              if: success()
              run: |
                  mhy config eslint prettier -io
                  npx lerna run config
                  npx lerna clean -y
                  npm i
                  npx lerna bootstrap
                  npx lerna link
                  npx lerna exec npm i
                  npx lerna run build
                  npx lerna run test
    # release:
    #     needs: test
    #     name: Release on node ${{ matrix.node_version }} and ${{ matrix.os }}
    #     runs-on: ${{ matrix.os }}
    #     strategy:
    #         matrix:
    #             node_version: [12]
    #             os: [ubuntu-latest]
    #     steps:
    #         - uses: actions/checkout@v1
    #         - name: Use Node.js ${{ matrix.node_version }}
    #           uses: actions/setup-node@v1
    #           with:
    #               node-version: 12
    #               registry-url: https://registry.npmjs.org/
    #         - name: Publishing...
    #           run: lerna publish
    #           env:
    #               NODE_AUTH_TOKEN: ${{secrets.npm_token}}
